# Generated by Django 6.0.1 on 2026-01-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_oreder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='oreder',
            new_name='order',
        ),
    ]
